"""
Script to compute the average L2 norms of baseline model activations. 
Loads pre-computed baseline activation tensors and calculates the mean L2 norm across the feature (d_model) dimension for each target layer. 
These scaling factors are required to calibrate the magnitude of activation steering vectors later in the experiments.

Structure:
- `compute_average_norms()`: load the activation dictionary, apply `torch.linalg.norm` over each feature dimension, calculate the mean per layer, and save the resulting dictionary.
"""


import os
import torch
import logging

# ==========================================
# Configuration
# ==========================================
MODEL_SLUG = "Qwen3-8B"
NUM_SAMPLES = 20000
VECTOR_DIR = os.path.join("baseline_vectors", MODEL_SLUG )
#"/home/ines/Reasoning-activations/reasoning_vectors/Qwen3-8B/fineweb_activations_20000.pt"
# os.path.join("reasoning_vectors", MODEL_SLUG, "fineweb")

# This is the file generated by `run_fw_pass.py --type baseline`
BASELINE_ACTIVATIONS_FILE = os.path.join(VECTOR_DIR, f"fineweb_activations_{NUM_SAMPLES}.pt")
OUTPUT_NORMS_FILE = os.path.join(VECTOR_DIR, f"fineweb_activations_{NUM_SAMPLES}_avg_norms.pt")

def compute_average_norms():
    logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
    
    if not os.path.exists(BASELINE_ACTIVATIONS_FILE):
        logging.error(f"File not found: {BASELINE_ACTIVATIONS_FILE}")
        return

    logging.info(f"Loading baseline activations from {BASELINE_ACTIVATIONS_FILE}...")
    data = torch.load(BASELINE_ACTIVATIONS_FILE, map_location="cpu")
    
    layers_dict = data.get("layers", {})
    avg_norms = {}
    
    logging.info("Computing average L2 norm per layer...")
    for layer, activations in layers_dict.items():
        # activations shape: [num_samples, d_model]
        # Compute the L2 norm for each sample across the d_model dimension
        # norms shape: [num_samples]
        norms = torch.linalg.norm(activations.to(torch.float32), dim=-1)
        
        # Calculate the mean of these norms
        avg_norm = norms.mean().item()
        avg_norms[layer] = avg_norm
        
        logging.info(f"Layer {layer}: Average Norm = {avg_norm:.4f}")
        
    # Save the dictionary mapping layer -> avg_norm
    output_data = {
        "metadata": data.get("metadata", {}),
        "avg_norms": avg_norms
    }
    
    torch.save(output_data, OUTPUT_NORMS_FILE)
    logging.info(f"Saved average norms to {OUTPUT_NORMS_FILE}")

if __name__ == "__main__":
    compute_average_norms()